// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4EL9r_EzSzW7F-A8mMGtMSP8mMizOfBU',
    appId: '1:412207332205:web:06fc7865dcd7d568cf3864',
    messagingSenderId: '412207332205',
    projectId: 'login-cfb27',
    authDomain: 'login-cfb27.firebaseapp.com',
    storageBucket: 'login-cfb27.firebasestorage.app',
    measurementId: 'G-G9DGQ4ZJFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZumI5YWH662nH10hjX_EMHCbUimE9ac8',
    appId: '1:412207332205:android:bb798ee9f8ac3bddcf3864',
    messagingSenderId: '412207332205',
    projectId: 'login-cfb27',
    storageBucket: 'login-cfb27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDASwRZ79An2LmF85f0UpS0By9bAURvwX4',
    appId: '1:412207332205:ios:a807d7b482b22128cf3864',
    messagingSenderId: '412207332205',
    projectId: 'login-cfb27',
    storageBucket: 'login-cfb27.firebasestorage.app',
    iosBundleId: 'com.example.walletapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDASwRZ79An2LmF85f0UpS0By9bAURvwX4',
    appId: '1:412207332205:ios:a807d7b482b22128cf3864',
    messagingSenderId: '412207332205',
    projectId: 'login-cfb27',
    storageBucket: 'login-cfb27.firebasestorage.app',
    iosBundleId: 'com.example.walletapp',
  );
}
